### PR TITLE
Switch from Fedora to Ubuntu, and consolidate Windows scripts

### PR DESCRIPTION
**Pull request by vicha-w**
Dear F4D developers,

One of my colleagues has started working on Fluka, and she was interested in installing Fluka via your F4D solution. Unfortunately she couldn't install it on her Windows machine, so she asked me for help.

Upon inspection, I have pinpointed that the current F4D image in Docker Hub is based on Fedora 30. I have switched the F4D base image for this project from Fedora 30 to Ubuntu 20.04 LTS. Please refer to https://github.com/flukadocker/F4D_baseimage/pull/2 for more information.

After fixing the problem for my colleague, I have received several requests for help from other people who are using their Windows machine and cannot install F4D. I then fixed the Windows scripts and tested on their Windows 10 Home machines with success.

However, there is one issue that I do not understand. I have noticed that you decided to use glibc2.17 in install_linux.sh script. Is this decision based on the fact that the base image is still using Fedora 30, or are there any other reason to use that particular version of glibc?

Please let me know if you need any further information or need me to commit any further changes.

Yours faithfully,
Vichayanun

### CODE REVIEW

**Comment by flukadocker** [comment]
@vicha-w thank you very much! As you said, we stay with fedora 30 because of python2. I'll have a look to your scripts and come back to you
Many thanks again
Paola

**Comment by vicha-w** [comment]
Hi @flukadocker. 

It has been more than a month now since your last reply. Do you have any updates on this pull request? Please let me know if you would like me to do any further changes.

Best regards,
Vichayanun

**Comment by vicha-w** [comment]
Hi @flukadocker,

It has been more than a year now since your last reply. Is this project still active?

Best regards,
Vichayanun

**Comment by flukadocker** [comment]
Hi Vichayanun
thank you again for your collaboration.
Finally, we decided to stay with fedora, because the main development is 
on fedora.
I updated the image to fedora37. The reason why we had an old fedora 
version was the compatibility with python2 for Flair.
  Now that we have a python3  version of flair we should be able to keep 
in pace with the latest fedora.
I understand that this was not your proposal.. but it makes things 
easier for us.
Hope to hear from you again
Paola

**Comment by vicha-w** [comment]
Dear Paola,

Thank you for your reply on this issue. I am glad that there is a version of FLUKA on Python 3 at last, so that we don't have to rely on other distros that still keep Python 2 around. I hope that people will be able to use your F4D solution without this issue.

Since the latest version of FLUKA is based on Python 3 now, Ubuntu-based F4D solution is not needed anymore, so I will close this PR.

Best regards,
Vichayanun

**Pull request closed without merging**
